<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PackageId>OLS.Lib.BoletoNetCore</PackageId>
    <title>OLS.Lib.BoletoNetCore</title>
    <version>1.0.3</version>
    <authors>OLS Tecnologia</authors>
    <!--<owners>BoletoNetCore</owners>-->
    <!--<projectUrl>https://github.com/BoletoNet/BoletoNetCore/</projectUrl>
    <iconUrl>https://https://avatars2.githubusercontent.com/u/10621326?v=3amp;s=200</iconUrl>-->
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>
      Fork da biblioteca BoletoNetCore que implementa a emissão e impressão de Boletos Bancários, geração de Arquivo de Remessa (CNAB 240 e 400) e leitura do Arquivo de Retorno (CNAB 240 e 400).
    </description>
    <!--<summary>BoletoNetCore is a library developed for use in Brazil, given it has been programmed with Brazilian retail legislation and business rules for bank registered billing integration.</summary>-->
    <!--<releaseNotes>A versão 3.0 está sendo reescrita. Alguns bancos/carteiras podem não estar disponíveis.</releaseNotes>-->
    <!--<tags>boleto cnab banco</tags>-->
    <TargetFramework>netstandard2.0</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AssemblyVersion>25.7.9323.0</AssemblyVersion>
    <FileVersion>25.7.9323.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Imagens\*" />
    <EmbeddedResource Include="BoletoImpressao\**\*.css" />
    <EmbeddedResource Include="BoletoImpressao\**\*.jpg" />
    <EmbeddedResource Include="BoletoImpressao\**\*.jpeg" />
    <EmbeddedResource Include="BoletoImpressao\**\*.html" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="BoletoImpressao\Parts\Pix.html" />
    <None Remove="Imagens\085.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.6" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.3" />
    <PackageReference Include="System.Net.Http.Json" Version="7.0.1" />
  </ItemGroup>


</Project>
